import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="px-8">
            <Header />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
